name: test-clang-format

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.16.2
      if: github.event.pull_request.merged == true
      with:
        extensions: 'h,cpp,c'
        clangFormatVersion: 16
        inplace: True
        source: './src/'
        exclude: './lib ./external'
        style: mozilla

    - uses: EndBug/add-and-commit@v9
      with:
        author_name: Clang Robot
        author_email: robot@example.com
        message: 'Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
